In [1]:
import sklearn.datasets as datasets
import pandas as pd

iris = datasets.load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
y = iris.target

#%%
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(df, y)
yhat = dtree.predict(df)
y - yhat
#%%

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
# Visualization
from sklearn.externals.six import StringIO
from IPython.display import Image
from sklearn.tree import export_graphviz
import pydotplus

dot_data = StringIO()
export_graphviz(dtree, out_file=dot_data,
                filled=True, rounded=True,
                special_characters=True)
graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
Image(graph.create_png())


InvocationException: GraphViz's executables not found

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_moons
#generate a dataset
X,y = make_moons(n_samples=100, noise=0.25, random_state=42)
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

C:\ProgramData\Anaconda3\envs\DataScienceRetreat\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [ ]:
print(X_train.shape)
print(y_train.shape)

In [ ]:
forest = RandomForestClassifier(n_estimators=5, random_state=42)
forest.fit(X_train, y_train)

### Cancer dataset

In [10]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
from sklearn.ensemble import RandomForestClassifier

In [11]:
df_cancer = pd.DataFrame(cancer.data, columns=cancer.feature_names)
print(df_cancer.info())
print(cancer.target)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
mean radius                569 non-null float64
mean texture               569 non-null float64
mean perimeter             569 non-null float64
mean area                  569 non-null float64
mean smoothness            569 non-null float64
mean compactness           569 non-null float64
mean concavity             569 non-null float64
mean concave points        569 non-null float64
mean symmetry              569 non-null float64
mean fractal dimension     569 non-null float64
radius error               569 non-null float64
texture error              569 non-null float64
perimeter error            569 non-null float64
area error                 569 non-null float64
smoothness error           569 non-null float64
compactness error          569 non-null float64
concavity error            569 non-null float64
concave points error       569 non-null float64
symmetry error             569 

In [12]:
X = cancer.data
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

(426, 30) (426,) (143, 30) (143,)


In [14]:
forest = RandomForestClassifier(n_estimators=1000, #number of trees
                                random_state=42,
                                n_jobs=-1 #for parallization
                               )
forest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=-1,
            oob_score=False, random_state=42, verbose=0, warm_start=False)

In [15]:
yhat = forest.predict(X_test)
y_test - yhat

array([ 0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0])

In [16]:
from sklearn.metrics import confusion_matrix

print(forest.score(X_test,y_test))
print(confusion_matrix(y_test, yhat))

0.965034965034965
[[51  3]
 [ 2 87]]


In [17]:
#Falsely classified instances
mask = ((y_test - yhat)!=0)
pd.DataFrame(X_test, columns=cancer.feature_names)[mask]

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
8          13.34         15.86           86.49      520.0          0.10780   
20         13.80         15.79           90.43      584.1          0.10070   
77         13.96         17.05           91.43      602.4          0.10960   
82         14.48         21.46           94.25      648.2          0.09444   
108        14.44         15.18           93.97      640.1          0.09970   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
8             0.15350         0.11690              0.06987         0.1942   
20            0.12800         0.07789              0.05069         0.1662   
77            0.12790         0.09789              0.05246         0.1908   
82            0.09947         0.12040              0.04938         0.2075   
108           0.10210         0.08487              0.05532         0.1724   

     mean fractal dimension           ...             worst radius  \
8                   0.06902           ...                    15.53   
20                  0.06566           ...                    16.57   
77                  0.06130           ...                    16.39   
82                  0.05636           ...                    16.21   
108                 0.06081           ...                    15.85   

     worst texture  worst perimeter  worst area  worst smoothness  \
8            23.19            96.66       614.9            0.1536   
20           20.86           110.30       812.4            0.1411   
77           22.07           108.10       826.0            0.1512   
82           29.25           108.40       808.9            0.1306   
108          19.85           108.60       766.9            0.1316   

     worst compactness  worst concavity  worst concave points  worst symmetry  \
8               0.4791           0.4858                0.1708          0.3527   
20              0.3542           0.2779                0.1383          0.2589   
77              0.3262           0.3209                0.1374          0.3068   
82              0.1976           0.3349                0.1225          0.3020   
108             0.2735           0.3103                0.1599          0.2691   

     worst fractal dimension  
8                    0.10160  
20                   0.10300  
77                   0.07957  
82                   0.06846  
108                  0.07683  

[5 rows x 30 columns]

In [19]:
feature_importance = forest.feature_importances_
dict(zip(cancer.feature_names, feature_importance))

{'mean radius': 0.04346585230596159,
 'mean texture': 0.015928973139440566,
 'mean perimeter': 0.044238364853761425,
 'mean area': 0.041625760957480946,
 'mean smoothness': 0.007291310193382912,
 'mean compactness': 0.013719599706060808,
 'mean concavity': 0.05466737104739361,
 'mean concave points': 0.10007563305033314,
 'mean symmetry': 0.004569942992338008,
 'mean fractal dimension': 0.004509525703954339,
 'radius error': 0.016847354073597436,
 'texture error': 0.0051431613617983684,
 'perimeter error': 0.010489458208376549,
 'area error': 0.03700431527743481,
 'smoothness error': 0.00458806914354015,
 'compactness error': 0.004199400583714842,
 'concavity error': 0.006818127215645574,
 'concave points error': 0.0052542982530430936,
 'symmetry error': 0.004621058520883709,
 'fractal dimension error': 0.005690024338204541,
 'worst radius': 0.0962616594508193,
 'worst texture': 0.0192784600810795,
 'worst perimeter': 0.10732632808202534,
 'worst area': 0.11573589617339533,
 'worst smo

In [39]:
from sklearn.ensemble import GradientBoostingClassifier
X_train, X_test, y_train, y_test = train_test_split(
    cancer.data,
    cancer.target,
    random_state = 42
)
gbrt = GradientBoostingClassifier(
    random_state = 42,
    n_estimators = 400,
    max_depth = 1,
    verbose = 1
)
gbrt.fit(X_train, y_train)
print("Accuracy on training set: {:0.3f}".format(gbrt.score(X_train, y_train)))
print("Accuracy on test set: {:0.3f}".format(gbrt.score(X_test, y_test)))

      Iter       Train Loss   Remaining Time 
         1           1.1867            0.00s
         2           1.0796            0.00s
         3           0.9877            0.00s
         4           0.9102            0.00s
         5           0.8441            0.00s
         6           0.7860            0.00s
         7           0.7320            0.00s
         8           0.6881            0.00s
         9           0.6481            0.00s
        10           0.6108            0.00s
        20           0.4007            0.00s
        30           0.3042            0.19s
        40           0.2483            0.14s
        50           0.2157            0.11s
        60           0.1894            0.09s
        70           0.1714            0.15s
        80           0.1575            0.13s
        90           0.1449            0.11s
       100           0.1359            0.16s
       200           0.0677            0.10s
       300           0.0378            0.04s
       40